{% set version = "12.0.0" %}
{% set sha256 = "49dc47c8697a1a0abd4ee51629a696d7bfe803662f2a7252a3b16fc75f3a8b50" %}

package:
  name: llvm-meta
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

test:
  commands:
    - echo 'Meta package for tracking llvm version'

about:
  home: http://github.com/conda-forge/llvm-meta-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.TXT
  license_family: BSD
  summary: Meta package for tracking llvm version

extra:
  recipe-maintainers:
    - isuruf
