{% set version = "13.0.0" %}
{% set sha256 = "408d11708643ea826f519ff79761fcdfc12d641a2510229eec459e72f8163020" %}

package:
  name: llvm-meta
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

test:
  commands:
    - echo 'Meta package for tracking llvm version'

about:
  home: http://github.com/conda-forge/llvm-meta-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.TXT
  license_family: BSD
  summary: Meta package for tracking llvm version

extra:
  recipe-maintainers:
    - isuruf
