travis:
  secure:
    BINSTAR_TOKEN: QZljp98tYfAVtjQy+O2HgEU0tC0JS+SGkmWZgEVMZQky2P8O/kowbRWoPQ3vXzKeewwYmnJXbZtx065lpCHTs2GWgShyaVTYejvxxfQhAkYyoGSLswCwi/Br6cjYsgRd7mj5qtIOsibjZmKLXsudHOkwQBpO2jEU9WvlPdFNkhJOio48QzhKqryAXMt4l01P6TZ33MiKNuf+m6Q2lIqi6ITtHKLQkvSViuSW7CC1HiYCvTjnHRCDc2W4379fdEo9DUPPFrHDSBSKh626dgrVjdiNC+9Rlqus8BmQvM6bPhwi6nPDGemaJjrOgHMTkVo1jD94pNRZChAnCkexb1AOdkGa0Kgx0ZwwBcoTy02sjlfnVQK3WH9ZV7QbgtJ82qJkguay3U/4FcHStNih4DRa6gc34losSDBxMtJnFNrLfDPQRA5nIBQ2tmFlxii5xI4ASjIs+xy45pUkyLaypJNzBsZYr4se7bTC76jM6B7hwSXf2JC94mIq5opGxw77imTTxwA4txMcDZ9fhrse7rTjUPp34Yp2c6h3kxSc2BaSxDeQ67DeQgTyNu8/ooln3tESfUhyX+KPYODyLMFIZZjhe0LqjqDXF6OSMuNHIk5GXiuBk58nwyBTKPeDCIxY4wlP4EwaFmAU4uKMTDOnYJPKZEzoZRGsj7BhBx5QPNbWdvA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
